#--------------------------------------------#
# Lugdunum-ThirdParty Appveyor configuration #
#--------------------------------------------#

# version format
version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: false

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - pip install -r requirements.txt

# to run your custom scripts instead of automatic MSBuild
build_script:
  - python build.py -vvvv

# to disable deployment
deploy: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off
