#--------------------------------------------#
# Lugdunum-ThirdParty Appveyor configuration #
#--------------------------------------------#

# version format
version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: false

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  - pip install -r requirements.txt

# scripts that run before the build
before_build:
  # TODO: Change the branch to dev
  - ps: |
      cd ..
      git clone https://github.com/Lugdunum3D/Lugdunum.git
      cd Lugdunum
      git checkout feature-gltf-integration-loader
      cd ../Lugdunum-ThirdParty

# to run your custom scripts instead of automatic MSBuild
build_script:
  - python build.py -vvvv -z Lugdunum-ThirdParty-Windows.zip ../Lugdunum/thirdparty.yml

# to disable deployment
deploy: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Lugdunum-ThirdParty-Windows.zip
    name: Lugdunum-ThirdParty-Windows.zip
